In [2]:
from transformers import pipeline, set_seed

import matplotlib.pyplot as plt

import pandas as pd
from datasets import load_dataset, load_metric

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

import nltk
from nltk.tokenize import sent_tokenize

from tqdm import tqdm
import torch

In [1]:
pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 15.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 15.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 17.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 16.1 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 2

In [3]:

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
model_ckpt = "google/pegasus-cnn_dailymail"

tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

model_pegasus = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/88.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/1.12k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/1.91M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.28G [00:00<?, ?B/s]

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-cnn_dailymail and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


generation_config.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

In [6]:
pip install py7zr

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 1.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 7.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.8/413.8 kB 12.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.9/138.9 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 5.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 16.6 MB/s eta 0:00:00


In [7]:
samsum_dataset = load_dataset('samsum')

The repository for samsum contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/samsum.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


Generating train split:   0%|          | 0/14732 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/819 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/818 [00:00<?, ? examples/s]

In [8]:
pipe_out =pipeline('summarization', model = model_ckpt)

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-cnn_dailymail and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [9]:
output =pipe_out(samsum_dataset['train'][0]['dialogue'])

Your max_length is set to 128, but your input_length is only 25. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=12)


In [10]:
# creating batches
def generate_batch_sized_chunks(list_of_elements, batch_size):
  for i in range(0, len(list_of_elements),batch_size):
    yield list_of_elements[i: i + batch_size]

In [ ]:
  len(list(generate_batch_sized_chunks(samsum_dataset['train']['summary'], 16)))

In [ ]:
def calculate_metric_on_test_ds(dataset, metric, model, tokenizer,
                               batch_size=16, device=device,
                               column_text="article",
                               column_summary="highlights"):
    article_batches = list(generate_batch_sized_chunks(dataset[column_text], batch_size))
    target_batches = list(generate_batch_sized_chunks(dataset[column_summary], batch_size))

    for article_batch, target_batch in tqdm(
        zip(article_batches, target_batches), total=len(article_batches)):

        inputs = tokenizer(article_batch, max_length=1024,  truncation=True,
                        padding="max_length", return_tensors="pt")

        summaries = model.generate(input_ids=inputs["input_ids"].to(device),
                         attention_mask=inputs["attention_mask"].to(device),
                         length_penalty=0.8, num_beams=8, max_length=128)
        ''' parameter for length penalty ensures that the model does not generate sequences that are too long. '''

        # Finally, we decode the generated texts,
        # replace the  token, and add the decoded texts with the references to the metric.
        decoded_summaries = [tokenizer.decode(s, skip_special_tokens=True,
                                clean_up_tokenization_spaces=True)
               for s in summaries]

        decoded_summaries = [d.replace("", " ") for d in decoded_summaries]


        metric.add_batch(predictions=decoded_summaries, references=target_batch)

    #  Finally compute and return the ROUGE scores.
    score = metric.compute()
    return score

In [18]:
zip(samsum_dataset['train']['summary'][0],samsum_dataset['train']['dialogue'][0])

In [24]:
for a,b in zip(samsum_dataset['train']['summary'][0:2],samsum_dataset['train']['dialogue'][0:2]):
  print(a,b)

Amanda baked cookies and will bring Jerry some tomorrow. Amanda: I baked  cookies. Do you want some?
Jerry: Sure!
Amanda: I'll bring you tomorrow :-)
Olivia and Olivier are voting for liberals in this election.  Olivia: Who are you voting for in this election? 
Oliver: Liberals as always.
Olivia: Me too!!
Oliver: Great


In [13]:
# generating summary on batches then we will check rouge score


[{'summary_text': "Amanda: I'll bring you tomorrow :-)<n>Amanda: I baked cookies. Do you want some?<n>Amanda: I'll bring you tomorrow :-)"}]

In [ ]:
rouge_metric = load_

In [26]:
inputs = tokenizer(samsum_dataset['train']['dialogue'][0], max_length=1024,  truncation=True,
                        padding="max_length", return_tensors="pt")

In [27]:
inputs

{'input_ids': tensor([[12195,   151,   125,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0]])}

In [36]:
inputs['input_ids'].shape

torch.Size([1, 1024])

In [37]:
inputs['attention_mask'].shape

torch.Size([1, 1024])

In [42]:
model_pegasus.generate(input_ids = inputs['input_ids'].to(device), attention_mask = inputs['attention_mask'].to(device), length_penalty = 0.8, num_beams = 8, max_length = 128 )

tensor([[    0, 12195,   151,   125,   131,   267,   650,   119,  3469, 29344,
           106, 41985,   151,   125,  7091,  3659,   107,   842,   119,   245,
           181,   152,   106, 41985,   151,   125,   131,   267,   650,   119,
          3469, 29344,     1]])

In [43]:
summaries = model_pegasus.generate(input_ids = inputs['input_ids'].to(device), attention_mask = inputs['attention_mask'].to(device), length_penalty = 0.8, num_beams = 8, max_length = 128 )

In [44]:
summaries

tensor([[    0, 12195,   151,   125,   131,   267,   650,   119,  3469, 29344,
           106, 41985,   151,   125,  7091,  3659,   107,   842,   119,   245,
           181,   152,   106, 41985,   151,   125,   131,   267,   650,   119,
          3469, 29344,     1]])

In [47]:
summaries.shape

torch.Size([1, 33])

In [46]:
for s in summaries:
  print(s)
  print(s.shape)

tensor([    0, 12195,   151,   125,   131,   267,   650,   119,  3469, 29344,
          106, 41985,   151,   125,  7091,  3659,   107,   842,   119,   245,
          181,   152,   106, 41985,   151,   125,   131,   267,   650,   119,
         3469, 29344,     1])
torch.Size([33])


In [ ]:
#Encoded summary of single training example predicted by pegasus model

In [ ]:
#Decoding the output

In [48]:
[tokenizer.decode(s, skip_special_tokens=True, clean_up_tokenization_spaces=True)  for s in summaries]

["Amanda: I'll bring you tomorrow :-)<n>Amanda: I baked cookies. Do you want some?<n>Amanda: I'll bring you tomorrow :-)"]

In [ ]:
# Now we can remove <n>

In [ ]:
# Now doing on a single batch_dataset

In [2]:
# creating batches

sumary_batch = list(generate_batch_sized_chunks(samsum_dataset['train']['dialogue'], 16))

NameError: name 'generate_batch_sized_chunks' is not defined

In [3]:
# let us determine what is the max_length of tokenizer for the longest dialogue in the dataset



In [ ]:
for i in sumary_batch:
  inputs = tokenizer(i, max_length=1024,  truncation=True,
                        padding="max_length", return_tensors="pt")
  print(inputs)
  summaries = model_pegasus.generate(input_ids=inputs["input_ids"].to(device),
                         attention_mask=inputs["attention_mask"].to(device),
                         length_penalty=0.8, num_beams=8, max_length=128)
  print(summaries)
  break

# as we can see it contains 16 examples of dialogues
# encoding is done seperatly for each batch.

{'input_ids': tensor([[12195,   151,   125,  ...,     0,     0,     0],
        [18038,   151,  2632,  ...,     0,     0,     0],
        [ 4776,   151,  4451,  ...,     0,     0,     0],
        ...,
        [13738,   151,   368,  ...,     0,     0,     0],
        [ 2603,  3275,   151,  ...,     0,     0,     0],
        [35612,   151,  3068,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}


In [ ]:
def calculating_rouge_score_batches(dataset, metric, model, tokenizer, batch_size, device, columns_text = 'dialogue', column_summary = 'summary'):

  article_batches = list(generate_batch_sized_chunks(dataset[columns_text], batch_size))
  target_batches = list(generate_batch_sized_chunks(dataset[column_summary], batch_size))

  for article_batch, target_batch in tqdm(
        zip(article_batches, target_batches), total=len(article_batches)):

        inputs = tokenizer(article_batch, max_length=1024,  truncation=True,
                        padding="max_length", return_tensors="pt")

        # inputs contain input_ids, attention_mask shape is 16, 1024

        summaries = model.generate(input_ids = inputs['input_ids'].to(device), attention_mask = inputs['attention_mask'],
                                   lenght_penalty = 0.8, num_beams = 8, max_length = 128)


        decoded_out = [tokenizer.decode(s, skip_special_tokens=True, clean_up_tokenization_spaces=True)  for s in summaries]


        decoded_summaries = [d.replace("", " ") for d in decoded_summaries]
        #

        metric.add_batch(predictions=decoded_summaries, references=target_batch)
  score = metric.compute
  return score






